# Generated by Django 5.2.6 on 2025-09-12 16:38

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria/Subárea')),
                ('slug', models.SlugField(blank=True, help_text='Este campo é preenchido automaticamente.', max_length=120, unique=True)),
                ('modulo', models.CharField(choices=[('ACORDOS', 'Acordos e Regulamentos'), ('OPORTUNIDADES', 'Oportunidades')], max_length=20, verbose_name='Módulo Principal')),
            ],
            options={
                'verbose_name': 'Categoria de Artigo',
                'verbose_name_plural': 'Categorias de Artigos',
                'ordering': ['modulo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo (Opcional)')),
                ('slug', models.SlugField(blank=True, help_text='Este campo é preenchido automaticamente a partir do título.', max_length=255, unique=True)),
                ('imagem_card', models.ImageField(help_text='Imagem que aparecerá na listagem principal. Tamanho ideal: 800x600 pixels.', upload_to='artigos/cards/', verbose_name='Imagem do Card')),
                ('tipo_conteudo', models.CharField(choices=[('TEXTO', 'Artigo de Texto'), ('PDF', 'Documento PDF')], default='TEXTO', max_length=10, verbose_name='Tipo de Conteúdo')),
                ('corpo_conteudo', tinymce.models.HTMLField(blank=True, help_text="Utilize este campo se o tipo de conteúdo for 'Artigo de Texto'.", verbose_name='Corpo do Artigo (se for texto)')),
                ('arquivo_pdf', models.FileField(blank=True, help_text="Faça o upload do arquivo se o tipo de conteúdo for 'Documento PDF'.", null=True, upload_to='artigos/pdfs/', verbose_name='Arquivo PDF')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado')], default='RASCUNHO', max_length=10, verbose_name='Status')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='artigos_autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artigos', to='gerenciamento_artigos.categoriaartigo', verbose_name='Categoria/Subárea')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
