# Generated by Django 5.2.6 on 2025-09-15 01:45

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('legislacao-fiscal-e-aduaneira', 'Legislações Fiscal e Aduaneira'), ('acordos-comerciais', 'Acordos Comerciais'), ('regulamentos-internacionais', 'Regulamentos Internacionais'), ('invista-em-roraima', 'Invista em Roraima'), ('prospeccao-de-mercados', 'Prospecção de Mercados')], max_length=100, verbose_name='Categoria/Subárea')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo (Opcional)')),
                ('slug', models.SlugField(blank=True, help_text='Este campo é preenchido automaticamente a partir do título.', max_length=255, unique=True)),
                ('imagem_card', models.ImageField(help_text='Imagem que aparecerá na listagem principal. Tamanho ideal: 800x600 pixels.', upload_to='artigos/cards/', verbose_name='Imagem do Card')),
                ('resumo_destaque', tinymce.models.HTMLField(blank=True, help_text='Conteúdo a ser exibido em uma caixa de destaque no topo do artigo.', null=True, verbose_name='Resumo / Pontos-Chave (Opcional)')),
                ('tipo_conteudo', models.CharField(choices=[('TEXTO', 'Artigo de Texto'), ('PDF', 'Documento PDF')], default='TEXTO', max_length=10, verbose_name='Tipo de Conteúdo')),
                ('corpo_conteudo', tinymce.models.HTMLField(blank=True, help_text="Utilize este campo se o tipo de conteúdo for 'Artigo de Texto'.", verbose_name='Corpo do Artigo (se for texto)')),
                ('arquivo_pdf', models.FileField(blank=True, help_text="Faça o upload do arquivo se o tipo de conteúdo for 'Documento PDF'.", null=True, upload_to='artigos/pdfs/', verbose_name='Arquivo PDF')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado')], default='RASCUNHO', max_length=10, verbose_name='Status')),
                ('meta_descricao', models.TextField(blank=True, help_text='Resumo do artigo para o Google (máximo de 160 caracteres).', max_length=160, null=True, verbose_name='Descrição para SEO')),
                ('palavras_chave', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula (ex: acordo comercial, legislação, roraima).', max_length=255, null=True, verbose_name='Palavras-chave')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='artigos_autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
