# Generated by Django 5.2.6 on 2025-09-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_artigos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='meta_descricao',
            field=models.TextField(blank=True, help_text='Resumo do artigo para o Google (máximo de 160 caracteres).', max_length=160, null=True, verbose_name='Descrição para SEO'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='palavras_chave',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula (ex: acordo comercial, legislação, roraima).', max_length=255, null=True, verbose_name='Palavras-chave'),
        ),
    ]
