# Generated by Django 5.2.6 on 2025-09-12 18:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_artigos', '0002_artigo_meta_descricao_artigo_palavras_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='resumo_destaque',
            field=tinymce.models.HTMLField(blank=True, help_text='Conteúdo a ser exibido em uma caixa de destaque no topo do artigo.', null=True, verbose_name='Resumo / Pontos-Chave (Opcional)'),
        ),
    ]
