# Generated by Django 5.2.6 on 2025-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_destino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudoapresentacaodestino',
            name='codigo_js',
            field=models.TextField(blank=True, help_text="Usado apenas para o tipo 'Animação'. Cole o código JS completo aqui.", verbose_name='Código JavaScript da Animação'),
        ),
        migrations.AlterField(
            model_name='conteudoapresentacaodestino',
            name='imagem',
            field=models.ImageField(blank=True, help_text="Usado apenas para o tipo 'Imagem Estática'.", null=True, upload_to='destino/apresentacao/', verbose_name='Arquivo de Imagem'),
        ),
        migrations.AlterField(
            model_name='conteudoapresentacaodestino',
            name='tipo_conteudo',
            field=models.CharField(choices=[('IMAGEM', 'Imagem Estática'), ('VIDEO', 'Vídeo (YouTube)'), ('ANIMACAO_JS', 'Animação com Código JavaScript')], default='IMAGEM', max_length=20, verbose_name='Tipo de Conteúdo'),
        ),
        migrations.AlterField(
            model_name='conteudoapresentacaodestino',
            name='video_url',
            field=models.URLField(blank=True, help_text="Usado apenas para o tipo 'Vídeo (YouTube)'.", null=True, verbose_name='URL do Vídeo do YouTube'),
        ),
    ]
