# Generated by Django 5.2.6 on 2025-09-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_destino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['grupo', 'nome'], 'verbose_name': 'Categoria (para Filtros)', 'verbose_name_plural': 'Categorias (para Filtros)'},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='grupo',
            field=models.CharField(choices=[('NATUREZA', 'Belezas da Natureza'), ('CULTURA', 'Cultura e Tradições'), ('SERVICO', 'Guia de Serviços')], default='', help_text='Associe esta categoria a uma das grandes áreas do módulo.', max_length=10, verbose_name='Grupo'),
            preserve_default=False,
        ),
    ]
