# Generated by Django 5.2.6 on 2025-09-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_destino', '0002_alter_categoria_options_remove_categoria_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontodeinteresse',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento_destino.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='servicoturistico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciamento_destino.categoria', verbose_name='Categoria'),
        ),
    ]
