# Generated by Django 5.2.6 on 2025-09-12 18:57

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_destino', '0002_alter_conteudoapresentacaodestino_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, help_text='Este campo é preenchido automaticamente.', max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('PONTO_DE_INTERESSE', 'Ponto de Interesse'), ('SERVICO_TURISTICO', 'Serviço Turístico')], help_text='Define se esta categoria é para Pontos de Interesse (Natureza, Cultura) ou Serviços (Hotel, Restaurante).', max_length=30, verbose_name='Tipo de Categoria')),
                ('icone', models.FileField(blank=True, help_text='Ícone que aparecerá no mapa. Use formato SVG, se possível.', null=True, upload_to='destino/icones/', verbose_name='Ícone (SVG)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='conteudoapresentacaodestino',
            name='em_exibicao',
            field=models.BooleanField(default=False, help_text='Apenas um conteúdo pode estar em exibição.', verbose_name='Em exibição na página?'),
        ),
        migrations.CreateModel(
            name='PontoDeInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título do Ponto de Interesse')),
                ('slug', models.SlugField(blank=True, help_text='Preenchido automaticamente a partir do título.', max_length=255, unique=True)),
                ('descricao_curta', models.TextField(help_text='Texto que aparece na janela do mapa (máx. 250 caracteres).', max_length=250, verbose_name='Descrição Curta')),
                ('descricao_completa', tinymce.models.HTMLField(help_text='Toda a história e detalhes do local.', verbose_name='Descrição Completa')),
                ('imagem_principal', models.ImageField(help_text='A imagem de maior destaque na página do local.', upload_to='destino/pontos_interesse/', verbose_name='Imagem Principal')),
                ('latitude', models.DecimalField(decimal_places=7, help_text='Coordenada de latitude. Ex: 2.8235241', max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, help_text='Coordenada de longitude. Ex: -60.6758335', max_digits=10, verbose_name='Longitude')),
                ('informacoes_praticas', tinymce.models.HTMLField(help_text="Use listas e negrito para formatar dicas como 'O que levar', 'Melhor época', 'Como chegar', etc.", verbose_name='Informações Práticas')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'PONTO_DE_INTERESSE'}, on_delete=django.db.models.deletion.PROTECT, to='gerenciamento_destino.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Ponto de Interesse',
                'verbose_name_plural': 'Pontos de Interesse',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='OrdemPontoRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ponto_de_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_destino.pontodeinteresse')),
            ],
            options={
                'verbose_name': 'Ordem do Ponto no Roteiro',
                'verbose_name_plural': 'Ordens dos Pontos nos Roteiros',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='destino/galerias/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=150, verbose_name='Legenda (Opcional)')),
                ('ponto_de_interesse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagens', to='gerenciamento_destino.pontodeinteresse', verbose_name='Ponto de Interesse')),
            ],
            options={
                'verbose_name': 'Imagem da Galeria',
                'verbose_name_plural': 'Imagens da Galeria',
            },
        ),
        migrations.CreateModel(
            name='Roteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título do Roteiro')),
                ('slug', models.SlugField(blank=True, help_text='Preenchido automaticamente a partir do título.', max_length=255, unique=True)),
                ('descricao', tinymce.models.HTMLField(verbose_name='Descrição do Roteiro')),
                ('imagem_capa', models.ImageField(upload_to='destino/roteiros/', verbose_name='Imagem de Capa do Roteiro')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('pontos_de_interesse', models.ManyToManyField(through='gerenciamento_destino.OrdemPontoRoteiro', to='gerenciamento_destino.pontodeinteresse', verbose_name='Pontos de Interesse')),
            ],
            options={
                'verbose_name': 'Roteiro Temático',
                'verbose_name_plural': 'Roteiros Temáticos',
            },
        ),
        migrations.AddField(
            model_name='ordempontoroteiro',
            name='roteiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_destino.roteiro'),
        ),
        migrations.CreateModel(
            name='ServicoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Estabelecimento/Serviço')),
                ('descricao', models.TextField(blank=True, max_length=500, verbose_name='Descrição Breve')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, verbose_name='Website / Rede Social')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude (Opcional)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude (Opcional)')),
                ('publicado', models.BooleanField(default=False, verbose_name='Publicado?')),
                ('categoria', models.ForeignKey(limit_choices_to={'tipo': 'SERVICO_TURISTICO'}, on_delete=django.db.models.deletion.PROTECT, to='gerenciamento_destino.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço Turístico',
                'verbose_name_plural': 'Serviços Turísticos',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
