# Generated by Django 5.2.6 on 2025-09-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_destino', '0003_alter_pontodeinteresse_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='grupo',
            field=models.CharField(choices=[('NATUREZA', 'Belezas da Natureza'), ('CULTURA', 'Cultura e Tradições')], help_text='Associe esta categoria a uma das grandes áreas do módulo.', max_length=10, verbose_name='Grupo'),
        ),
        migrations.DeleteModel(
            name='ServicoTuristico',
        ),
    ]
