# Generated by Django 5.2.6 on 2025-09-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição interna do logotipo (ex: Logo Governo RR).', max_length=100)),
                ('imagem', models.ImageField(help_text='Faça upload da imagem do logo.', upload_to='logos/header/')),
                ('link_url', models.URLField(blank=True, help_text='Link opcional para o logo.', null=True)),
            ],
            options={
                'verbose_name': 'Logotipo do Cabeçalho',
                'verbose_name_plural': '1. Manutenção Logotipos (Cabeçalho)',
            },
        ),
        migrations.CreateModel(
            name='ImagemApresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FUNDO', 'Imagem de Fundo do Site'), ('HERO', 'Imagem do Carrossel (Hero)')], default='HERO', max_length=5)),
                ('descricao', models.CharField(help_text='Descrição interna da imagem (ex: Paisagem RR).', max_length=100)),
                ('imagem', models.ImageField(help_text='Imagem principal da home page ou fundo do site.', upload_to='apresentacao/')),
                ('link_url', models.URLField(blank=True, help_text='Link opcional para a imagem.', null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Use 0, 1, 2... para definir a ordem de aparição no carrossel.')),
            ],
            options={
                'verbose_name': 'Imagem de Apresentação',
                'verbose_name_plural': '2. Manutenção Imagens (Fundo e Hero)',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parceiro', models.CharField(help_text='Nome do parceiro.', max_length=100)),
                ('imagem', models.ImageField(help_text='Logo do parceiro para o carrossel do rodapé.', upload_to='logos/parceiros/')),
                ('link_url', models.URLField(blank=True, help_text='Link opcional para o site do parceiro.', null=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Use 0, 1, 2... para definir a ordem no carrossel.')),
            ],
            options={
                'verbose_name': 'Logotipo de Parceiro',
                'verbose_name_plural': '3. Manutenção Logotipos (Parceiros)',
                'ordering': ['ordem'],
            },
        ),
    ]
