# Generated by Django 5.2.6 on 2025-09-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headerlogo',
            options={'verbose_name': 'Logotipo da SEADI', 'verbose_name_plural': 'Logotipos da SEADI'},
        ),
        migrations.AlterModelOptions(
            name='imagemapresentacao',
            options={'ordering': ['ordem'], 'verbose_name': 'Imagem', 'verbose_name_plural': 'Imagens para Fundo Global e Carrossel de Apresentação'},
        ),
        migrations.AlterModelOptions(
            name='partnerlogo',
            options={'ordering': ['ordem'], 'verbose_name': 'Logotipo do Parceiro Institucional', 'verbose_name_plural': 'Logotipos dos Parceiros Institucionais'},
        ),
    ]
