# Generated by Django 5.2.6 on 2025-09-11 14:33

import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, help_text='Este campo é preenchido automaticamente.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Notícia',
                'verbose_name_plural': '1. Categorias de Notícias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título da Notícia')),
                ('slug', models.SlugField(blank=True, help_text='Preenchido automaticamente a partir do título.', max_length=255, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo (Opcional)')),
                ('corpo', tinymce.models.HTMLField(verbose_name='Corpo da Notícia')),
                ('imagem_card', models.ImageField(help_text='Imagem principal da matéria.', upload_to='noticias/cards/', verbose_name='Imagem de Capa/Card')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado')], default='RASCUNHO', max_length=10, verbose_name='Status')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias_autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categorias', models.ManyToManyField(related_name='noticias', to='gerenciamento_noticias.categoria', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': '2. Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Um número menor aparece primeiro (0, 1, 2...).', verbose_name='Ordem de Exibição')),
                ('noticia', models.ForeignKey(help_text='Selecione a notícia que aparecerá no carrossel.', on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_noticias.noticia', verbose_name='Notícia em Destaque')),
            ],
            options={
                'verbose_name': 'Notícia em Destaque',
                'verbose_name_plural': '3. Notícias em Destaque',
                'ordering': ['ordem'],
            },
        ),
    ]
