# Generated by Django 5.2.6 on 2025-09-16 02:44

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerNoticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conteudo', models.CharField(choices=[('IMAGEM_TEXTO', 'Imagem de Fundo com Texto Sobreposto'), ('TEXTO_ESTATICO', 'Apenas Texto Estático'), ('ANIMACAO_JS', 'Animação com Código JavaScript')], default='IMAGEM_TEXTO', max_length=20, verbose_name='Tipo de Conteúdo do Banner')),
                ('titulo', models.CharField(blank=True, max_length=150, verbose_name='Título')),
                ('subtitulo', models.TextField(blank=True, verbose_name='Subtítulo/Texto (Opcional)')),
                ('imagem_fundo', models.ImageField(blank=True, help_text="Usado apenas para o tipo 'Imagem de Fundo'.", null=True, upload_to='noticias/banners/', verbose_name='Imagem de Fundo')),
                ('codigo_js', models.TextField(blank=True, help_text='Cole aqui o script completo da animação. Ele será renderizado na página.', verbose_name='Código JavaScript')),
                ('ativo', models.BooleanField(default=False, help_text='Apenas um banner pode estar ativo por vez.', verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Artifício de Apresentação do Módulo',
                'verbose_name_plural': 'Artifícios de Apresentação do Módulo',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, help_text='Este campo é preenchido automaticamente.', max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Tópico',
                'verbose_name_plural': 'Tópicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, unique=True, verbose_name='Título da Notícia')),
                ('slug', models.SlugField(blank=True, help_text='Preenchido automaticamente a partir do título.', max_length=255, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo (Opcional)')),
                ('imagem_card', models.ImageField(help_text='Imagem para as listagens. Tamanho ideal: 800x600 pixels.', upload_to='noticias/cards/', verbose_name='Imagem do Card')),
                ('imagem_destaque', models.ImageField(help_text='Imagem principal da matéria. Tamanho ideal: 1200x600 pixels.', upload_to='noticias/destaques/', verbose_name='Imagem de Destaque')),
                ('corpo', tinymce.models.HTMLField(verbose_name='Corpo da Notícia')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PUBLICADO', 'Publicado')], default='RASCUNHO', max_length=10, verbose_name='Status')),
                ('meta_descricao', models.TextField(blank=True, help_text='Resumo da notícia para o Google (máximo de 160 caracteres).', max_length=160, null=True, verbose_name='Descrição para SEO')),
                ('palavras_chave', models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula (ex: economia, agronegócio, roraima).', max_length=255, null=True, verbose_name='Palavras-chave')),
                ('data_publicacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='noticias_autor', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('categorias', models.ManyToManyField(related_name='noticias', to='gerenciamento_noticias.categoria', verbose_name='Categorias')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Uma lista de tags separadas por vírgula.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Um número menor aparece primeiro (0, 1, 2...).', verbose_name='Ordem de Exibição')),
                ('noticia', models.ForeignKey(help_text='Selecione a notícia que aparecerá no carrossel.', on_delete=django.db.models.deletion.CASCADE, to='gerenciamento_noticias.noticia', verbose_name='Notícia em Destaque')),
            ],
            options={
                'verbose_name': 'Publicação em Destaque',
                'verbose_name_plural': 'Publicações em Destaque',
                'ordering': ['ordem'],
            },
        ),
    ]
