# Generated by Django 5.2.6 on 2025-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_noticias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerNoticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do Banner')),
                ('subtitulo', models.TextField(blank=True, null=True, verbose_name='Subtítulo/Texto (Opcional)')),
                ('imagem_fundo', models.ImageField(upload_to='noticias/banners/', verbose_name='Imagem de Fundo')),
                ('ativo', models.BooleanField(default=False, help_text='Apenas um banner pode estar ativo por vez.', verbose_name='Está ativo?')),
            ],
            options={
                'verbose_name': 'Banner da Página de Notícias',
                'verbose_name_plural': '0. Banners da Página de Notícias',
            },
        ),
    ]
