# Generated by Django 5.2.6 on 2025-09-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannernoticias',
            name='codigo_js',
            field=models.TextField(blank=True, help_text='Cole aqui o script completo da animação. Ele será renderizado na página.', verbose_name='Código JavaScript'),
        ),
        migrations.AddField(
            model_name='bannernoticias',
            name='tipo_conteudo',
            field=models.CharField(choices=[('IMAGEM_TEXTO', 'Imagem de Fundo com Texto Sobreposto'), ('TEXTO_ESTATICO', 'Apenas Texto Estático'), ('ANIMACAO_JS', 'Animação com Código JavaScript')], default='IMAGEM_TEXTO', max_length=20, verbose_name='Tipo de Conteúdo do Banner'),
        ),
        migrations.AlterField(
            model_name='bannernoticias',
            name='imagem_fundo',
            field=models.ImageField(blank=True, help_text="Usado apenas para o tipo 'Imagem de Fundo'.", null=True, upload_to='noticias/banners/', verbose_name='Imagem de Fundo'),
        ),
        migrations.AlterField(
            model_name='bannernoticias',
            name='subtitulo',
            field=models.TextField(blank=True, default='', verbose_name='Subtítulo/Texto (Opcional)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bannernoticias',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Título'),
        ),
    ]
