# Generated by Django 5.2.6 on 2025-09-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_noticias', '0002_bannernoticias_codigo_js_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannernoticias',
            options={'verbose_name': 'Artifício de Apresentação do Módulo', 'verbose_name_plural': 'Artifícios de Apresentação do Módulo'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'Tópico', 'verbose_name_plural': 'Tópicos'},
        ),
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_publicacao'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='noticiadestaque',
            options={'ordering': ['ordem'], 'verbose_name': 'Publicação em Destaque', 'verbose_name_plural': 'Publicações em Destaque'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagem_destaque',
            field=models.ImageField(default='', help_text='Imagem principal da matéria. Tamanho ideal: 1200x600 pixels.', upload_to='noticias/destaques/', verbose_name='Imagem de Destaque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='meta_descricao',
            field=models.TextField(blank=True, help_text='Resumo da notícia para o Google (máximo de 160 caracteres).', max_length=160, null=True, verbose_name='Descrição para SEO'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='palavras_chave',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula (ex: economia, agronegócio, roraima).', max_length=255, null=True, verbose_name='Palavras-chave'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem_card',
            field=models.ImageField(help_text='Imagem para as listagens. Tamanho ideal: 800x600 pixels.', upload_to='noticias/cards/', verbose_name='Imagem do Card'),
        ),
    ]
