# Generated by Django 5.2.6 on 2025-09-11 17:01

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_noticias', '0002_bannernoticias'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Uma lista de tags separadas por vírgula.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
