# Generated by Django 5.2.6 on 2025-09-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoApresentacaoOportunidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição Interna')),
                ('tipo_conteudo', models.CharField(choices=[('IMAGEM', 'Imagem Estática'), ('VIDEO', 'Vídeo (YouTube)')], default='IMAGEM', max_length=10, verbose_name='Tipo de Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='oportunidades/apresentacao/', verbose_name='Arquivo de Imagem')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL do Vídeo do YouTube')),
                ('em_exibicao', models.BooleanField(default=False, verbose_name='Em exibição na página?')),
            ],
            options={
                'verbose_name': 'Conteúdo de Apresentação (Oportunidades)',
                'verbose_name_plural': '4. Conteúdos de Apresentação (Oportunidades)',
            },
        ),
    ]
