# Generated by Django 5.2.6 on 2025-09-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoApresentacaoAcordos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text="Ex: 'Imagem de aperto de mãos'.", max_length=200, verbose_name='Descrição Interna')),
                ('tipo_conteudo', models.CharField(choices=[('IMAGEM', 'Imagem Estática'), ('VIDEO', 'Vídeo (YouTube)')], default='IMAGEM', max_length=10, verbose_name='Tipo de Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='acordos/apresentacao/', verbose_name='Arquivo de Imagem')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL do Vídeo do YouTube')),
                ('em_exibicao', models.BooleanField(default=False, help_text='Apenas um conteúdo pode estar em exibição.', verbose_name='Em exibição na página?')),
            ],
            options={
                'verbose_name': 'Artifício de Apresentação do Módulo',
                'verbose_name_plural': 'Artifícios de Apresentação do Módulo',
            },
        ),
    ]
