# Generated by Django 5.2.6 on 2025-09-11 13:51

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoInteligencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DADOS_ESTRUTURAIS', 'Dados Estruturais'), ('ANALISES_E_ARTIGOS', 'Análises e Artigos')], max_length=50, verbose_name='Categoria do Conteúdo')),
                ('titulo_card', models.CharField(help_text='Texto que aparece na listagem de cards da seção.', max_length=100, verbose_name='Título no Card')),
                ('imagem_card', models.ImageField(help_text='Imagem que aparece na listagem de cards.', upload_to='inteligencia_mercado/cards/', verbose_name='Imagem de Capa do Card')),
                ('titulo_pagina', models.CharField(help_text='Título exibido no topo da página ao abrir o conteúdo.', max_length=200, verbose_name='Título Principal da Página')),
                ('subtitulo_pagina', models.CharField(blank=True, help_text='Texto curto opcional que aparece abaixo do título principal.', max_length=300, null=True, verbose_name='Subtítulo da Página')),
                ('corpo_conteudo', tinymce.models.HTMLField(help_text='O texto principal do artigo. Use a tag [grafico:sua-chave-aqui] para inserir um gráfico no texto.', verbose_name='Conteúdo Principal')),
                ('publicado', models.BooleanField(default=False, help_text='Marque esta opção para que o conteúdo apareça no site para os usuários.', verbose_name='Visível para o público?')),
            ],
            options={
                'verbose_name': 'Conteúdo de Inteligência',
                'verbose_name_plural': '1. Conteúdos de Inteligência',
                'ordering': ['categoria', 'titulo_card'],
            },
        ),
        migrations.CreateModel(
            name='Grafico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_grafico', models.CharField(choices=[('OPTION_SIMPLE', 'Objeto Option Simples'), ('SCRIPT_COMPLETO', 'Script de Animação Completo')], default='OPTION_SIMPLE', help_text="Escolha 'Objeto Option Simples' se você está colando apenas o JSON de configuração. Escolha 'Script de Animação Completo' para colar um script JavaScript auto-executável.", max_length=20, verbose_name='Tipo de Gráfico')),
                ('titulo', models.CharField(help_text='Um nome único para identificar o gráfico no painel.', max_length=200, unique=True, verbose_name='Título Interno do Gráfico')),
                ('chave', models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Chave Única')),
                ('codigo_js_echarts', models.TextField(help_text="Cole aqui o objeto 'option' ou o script completo, de acordo com o tipo selecionado acima.", verbose_name='Código JavaScript')),
                ('is_grafico_principal', models.BooleanField(default=False, help_text='Marque esta opção para que este gráfico apareça na página inicial do módulo de Inteligência de Mercado. Apenas um pode ser marcado.', verbose_name='É o gráfico principal da página de Inteligência?')),
            ],
            options={
                'verbose_name': 'Gráfico',
                'verbose_name_plural': '2. Gráficos para Conteúdos',
            },
        ),
        migrations.CreateModel(
            name='TermoGlossario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100, unique=True, verbose_name='Termo')),
                ('explicacao', tinymce.models.HTMLField(help_text='Use as ferramentas de formatação para criar uma explicação clara e didática.', verbose_name='Explicação do Termo')),
            ],
            options={
                'verbose_name': 'Termo do Glossário',
                'verbose_name_plural': '3. Glossário de Termos',
                'ordering': ['termo'],
            },
        ),
    ]
