# Generated by Django 5.2.6 on 2025-09-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_inteligencia_mercado', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudointeligencia',
            options={'ordering': ['categoria', 'titulo_card'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='grafico',
            options={'verbose_name': 'Gráfico', 'verbose_name_plural': 'Gráficos'},
        ),
        migrations.AlterModelOptions(
            name='termoglossario',
            options={'ordering': ['termo'], 'verbose_name': 'Termo', 'verbose_name_plural': 'Termos'},
        ),
    ]
