# Generated by Django 5.2.6 on 2025-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_inteligencia_mercado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafico',
            name='is_grafico_principal',
            field=models.BooleanField(default=False, help_text='Marque esta opção para que este gráfico apareça na página inicial do módulo de Inteligência de Mercado. Apenas um pode ser marcado.', verbose_name='É o gráfico principal da página de Inteligência?'),
        ),
    ]
