# Generated by Django 5.2.6 on 2025-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_inteligencia_mercado', '0002_grafico_is_grafico_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafico',
            name='tipo_grafico',
            field=models.CharField(choices=[('OPTION_SIMPLE', 'Objeto Option Simples'), ('SCRIPT_COMPLETO', 'Script de Animação Completo')], default='OPTION_SIMPLE', help_text="Escolha 'Objeto Option Simples' se você está colando apenas o JSON de configuração. Escolha 'Script de Animação Completo' para colar um script JavaScript auto-executável.", max_length=20, verbose_name='Tipo de Gráfico'),
        ),
        migrations.AlterField(
            model_name='grafico',
            name='codigo_js_echarts',
            field=models.TextField(help_text="Cole aqui o objeto 'option' ou o script completo, de acordo com o tipo selecionado acima.", verbose_name='Código JavaScript'),
        ),
    ]
