# Generated by Django 5.2.6 on 2025-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_inteligencia_mercado', '0002_alter_conteudointeligencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudointeligencia',
            name='categoria',
            field=models.CharField(choices=[('DADOS_ESTRUTURAIS', 'Dados Estruturais'), ('ANALISES_E_ARTIGOS', 'Análises')], max_length=50, verbose_name='Categoria do Conteúdo'),
        ),
    ]
