# Generated by Django 5.2.6 on 2025-09-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_inteligencia_mercado', '0003_grafico_tipo_grafico_alter_grafico_codigo_js_echarts'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteudointeligencia',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Marque esta opção para que o conteúdo apareça no site para os usuários.', verbose_name='Visível para o público?'),
        ),
    ]
