# Generated by Django 5.2.6 on 2025-09-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraChaveAprenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=100, unique=True, verbose_name='Palavra-Chave')),
                ('peso', models.PositiveIntegerField(default=10, help_text='Um número maior significa que a palavra aparecerá maior na nuvem. Ex: de 10 a 100.', verbose_name='Peso (Tamanho)')),
            ],
            options={
                'verbose_name': 'Palavra-Chave (Aprenda Comex)',
                'verbose_name_plural': '1. Palavras-Chave (Aprenda Comex)',
                'ordering': ['-peso', 'palavra'],
            },
        ),
    ]
