# Generated by Django 5.2.6 on 2025-09-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_aprenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conteudoapresentacaoaprenda',
            options={'verbose_name': 'Artifício de Apresentação do Módulo', 'verbose_name_plural': 'Artifícios de Apresentação do Módulo'},
        ),
    ]
