# Generated by Django 5.2.6 on 2025-09-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoApresentacaoVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text="Ex: 'Vídeo sobre como vender' ou 'Imagem da vitrine de produtos'.", max_length=200, verbose_name='Descrição Interna')),
                ('tipo_conteudo', models.CharField(choices=[('IMAGEM', 'Imagem Estática'), ('VIDEO', 'Vídeo (YouTube)')], default='IMAGEM', max_length=10, verbose_name='Tipo de Conteúdo')),
                ('imagem', models.ImageField(blank=True, help_text="Carregue uma imagem se o tipo for 'Imagem Estática'.", null=True, upload_to='vendas/apresentacao/', verbose_name='Arquivo de Imagem')),
                ('video_url', models.URLField(blank=True, help_text='Cole a URL normal do vídeo do YouTube.', null=True, verbose_name='URL do Vídeo do YouTube')),
                ('em_exibicao', models.BooleanField(default=False, help_text='Marque esta opção para que este conteúdo apareça na página. Apenas um pode estar em exibição.', verbose_name='Em exibição na página?')),
            ],
            options={
                'verbose_name': 'Conteúdo de Apresentação (Quero Vender)',
                'verbose_name_plural': '2. Conteúdos de Apresentação (Quero Vender)',
            },
        ),
    ]
