# Generated by Django 5.2.6 on 2025-09-16 03:03

import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_vender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('resposta', tinymce.models.HTMLField(verbose_name='Resposta')),
                ('publicada', models.BooleanField(default=False, verbose_name='Está publicada?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Pergunta Frequente',
                'verbose_name_plural': 'Perguntas Frequentes',
                'ordering': ['pergunta'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField(verbose_name='Pergunta do Usuário')),
                ('email_usuario', models.EmailField(max_length=254, verbose_name='E-mail do Usuário')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Resposta'), ('RESPONDIDA', 'Respondida')], default='PENDENTE', max_length=10, verbose_name='Status')),
                ('resposta', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Resposta do Administrador')),
                ('data_resposta', models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('identificador_unico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador Único')),
                ('resposta_foi_util', models.BooleanField(blank=True, choices=[(True, 'Útil'), (False, 'Não foi útil')], null=True, verbose_name='Avaliação do Usuário')),
            ],
            options={
                'verbose_name': 'Pergunta de Usuário',
                'verbose_name_plural': 'Perguntas de Usuários',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.AlterField(
            model_name='conteudoapresentacaovender',
            name='em_exibicao',
            field=models.BooleanField(default=False, help_text='Apenas um conteúdo pode estar em exibição.', verbose_name='Em exibição na página?'),
        ),
    ]
