# Generated by Django 5.2.6 on 2025-09-16 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_vender', '0002_perguntafrequente_perguntausuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEmpresariais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de preenchimento'), ('EM_ANALISE', 'Em Análise'), ('APROVADO', 'Aprovado'), ('REAVALIACAO', 'Aprovado (em Reavaliação)')], default='PENDENTE', max_length=20, verbose_name='Status do Cadastro')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(max_length=20, verbose_name='Inscrição Estadual')),
                ('atividade_principal', models.TextField(verbose_name='Atividade Comercial Principal')),
                ('atividades_secundarias', models.TextField(blank=True, verbose_name='Atividades Comerciais Secundárias')),
                ('documento_comprobatorio_empresa', models.FileField(upload_to='documentos/empresa/', verbose_name='Documento Comprobatório da Empresa')),
                ('nome_responsavel', models.CharField(max_length=255, verbose_name='Nome Completo do Responsável')),
                ('cpf_responsavel', models.CharField(max_length=14, verbose_name='CPF do Responsável')),
                ('cargo_responsavel', models.CharField(max_length=100, verbose_name='Cargo do Responsável')),
                ('email_responsavel', models.EmailField(max_length=254, verbose_name='E-mail para Contato Direto')),
                ('telefone_responsavel', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp para Contato')),
                ('documento_vinculo_responsavel', models.FileField(upload_to='documentos/responsavel/', verbose_name='Documento Comprobatório do Vínculo')),
                ('endereco', models.TextField(verbose_name='Endereço Completo')),
                ('telefone_institucional', models.CharField(blank=True, max_length=20, verbose_name='Telefone Institucional')),
                ('email_institucional', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Institucional')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('apresentacao_empresa', models.TextField(blank=True, verbose_name='Apresentação da Empresa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Dados Empresariais',
                'verbose_name_plural': 'Dados Empresariais',
            },
        ),
    ]
