# Generated by Django 5.2.6 on 2025-09-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('PERMISSIONARIO', 'Permissionário (Equipe Interna)'), ('EMPRESA', 'Empresa'), ('EMPREENDEDOR', 'Empreendedor'), ('APRENDIZ', 'Aprendiz (Aprenda Comex)')], default='EMPRESA_EMPREENDEDOR', max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
