# Generated by Django 5.2.6 on 2025-09-09 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_registros', '0002_alter_customuser_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpreendedorProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='empreendedor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_completo', models.CharField(blank=True, max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Perfil de Empreendedor',
                'verbose_name_plural': 'Perfis de Empreendedores',
            },
        ),
        migrations.CreateModel(
            name='EmpresaProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='empresa_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfis de Empresas',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('PERMISSIONARIO', 'Permissionário (Equipe Interna)'), ('EMPRESA', 'Empresa'), ('EMPREENDEDOR', 'Empreendedor'), ('APRENDIZ', 'Aprendiz (Aprenda Comex)')], max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
