# Generated by Django 5.2.6 on 2025-09-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_registros', '0003_empreendedorprofile_empresaprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ADMIN', [('PERMISSIONARIO', 'Permissionário (Equipe Interna)')]), ('EMPRESARIAL', [('EMPRESA', 'Empresa'), ('EMPREENDEDOR', 'Empreendedor')]), ('EDUCACIONAL', [('APRENDIZ', 'Aprendiz (Aprenda Comex)')])], max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
